[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[[edge_functions]]
  function = "geo-block"  # Name of your Edge Function file (without .js)
  path = "/*"            # Applies to all routes

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:;"
    Referrer-Policy = "strict-origin-when-cross-origin"
